### ISSUE TITLE
Improvement - "Button text looks smudged in comparison to Corporate UI 3.5.x"

### ISSUE THREAD

**Issue by mxuwku** [scania/scania-theme#102]
**Describe current situation**  
Text in buttons for example looks smudged in Scania theme incomparison to how they look in older version of Corporate UI 3.5.x

**Describe the improvement**  
Compare how the different solutions works and see if they can be made sharper again :)

**If applicable, please provide steps to reproduce**
_Steps to reproduce the behavior:_  
1. Go to 'https://scania.github.io/corporate-ui-site/components/buttons'
4. Compare with buttons from older versions of Corporate UI (3.5.x) see screenshots or visit repsective site.

**Screenshots**  
From https://scania.github.io/corporate-ui-site/components/buttons
![image](https://user-images.githubusercontent.com/39794299/70915659-845ac080-201a-11ea-8e57-8f7c875e4f3f.png)
From https://scania.github.io/corporate-ui-docs/corporate-ui/components/#buttons
![image](https://user-images.githubusercontent.com/39794299/70915715-a3f1e900-201a-11ea-8096-9a8c07f313af.png)

**Browser used**
Google Chrome 64 bit 79.0.3945.79

**Comment by helloimela** [comment]
Button improvement is in progress and will be implemented in version 4
