### ISSUE TITLE
Bug - Conflicts with NPM

### ISSUE THREAD

**Issue by corte** [scania/scania-theme#114]
**Describe the bug**  
While trying to upgrade from scania-theme 1.0.0-alpha.19 (could happen with 1.0.0 as well) to 1.0.0-0 NPM gets the version 1.0.0:
``` npm i scania-theme ```

**To Reproduce**   
_Steps to reproduce the behavior:_  
1. Have a project with any version of scania-theme other than 1.0.0-0 (in my case 1.0.0-alpha.19)
2. Run `npm install scania-theme`
3. Get version 1.0.0 instead of 1.0.0-0

**Expected behavior**  
The latest version should be added to the project, not 1.0.0 which is old.

**Screenshots**  
![image](https://user-images.githubusercontent.com/4606160/71715351-5bf00600-2e11-11ea-80ec-7e924dab0526.png)

**Version of Scania-theme**  
 1.0.0-alpha.19 to 1.0.0-0

**Framework and version**  
_If you use any specific framework please provide information_
- Framework: Angular
- Version: 8

**Additional context**   
Work-around is just running `npm i scania-theme@1.0.0-0` explicitly.

**Comment by mmexvr** [comment]
Good catch! We will look into this more when 1.0.1 if the problem still exist. 


You can either use `npm i scania-theme@1.0.0-0` or with tag `npm i scania-theme@latest ` or change directly in the package file to 1.0.0-0

**Comment by mmexvr** [comment]
#117 should have solved that issue now

**Comment by mmexvr** [comment]
This issue is related with npm, how the see the "-" as a pre-release
