### ISSUE TITLE
Feature - Buttons 4.0.0-beta

### ISSUE THREAD

**Issue by mmexvr** [scania/scania-theme#14]
**Is your feature request related to a problem? Please describe.**
Based on bootstrap 4 documentation

This is what need to be done to complete button task in #11 

https://getbootstrap.com/docs/4.3/components/buttons/

Master:
http://d1kybmg72qo0dt.cloudfront.net/build/global/branch/master/www/index.html

- [x] Default Button, E.g Font, Padding, Border-radius, font-weight
- [x] Colors
- [x] States, E.g Focus
- [x] ~~Button dark~~ 
- [x] Tags
- [x] ~~Outline~~
- [x] Sizes
- [x] Active state
- [x] Disabled
- [x] ~~Button plugin~~

**Comment by mmexvr** [comment]
#22 
Note: Dropdown have the class ".show", the intercation colors when the the dropdown is shown is incorrect.

**Comment by helloimela** [comment]
Merged to master PR #13
