### ISSUE TITLE
Feature - Tables 4.0.0-beta

### ISSUE THREAD

**Issue by mmexvr** [scania/scania-theme#16]
**Is your feature request related to a problem? Please describe.**
Based on bootstrap 4 documentation

This is what need to be done to complete Table task in #11 

https://getbootstrap.com/docs/4.3/content/tables/

Master:
http://d1kybmg72qo0dt.cloudfront.net/build/global/branch/master/www/index.html

- [x] Default table, Eg, font, padding, border-radius, font-weight margin, border
- [x] ~~Table-dark~~
- [x] Thead-head
- [x] ~~Thead-head Dark~~
- [x] Striped Rows
- [x] ~~Striped Rows Dark~~
- [x] Bordered 
- [x] ~~Bordered Dark~~
- [x] Borderless 
- [x] ~~Borderless Dark~~
- [x] ~~Hoverable rows~~ 
- [x] ~~Hoverable rows  Dark~~
- [x] ~~Small table~~
- [x] Table row colours
- [x] ~~Table row colours Dark~~
- [x] ~~Captions~~
- [x] ~~Resposive~~
- [x] ~~Breakpoint specific~~

**Comment by helloimela** [comment]
Merged to master PR #13
