### ISSUE TITLE
Feature - Button-groups 4.0.0-beta

### ISSUE THREAD

**Issue by mmexvr** [scania/scania-theme#18]
**Is your feature request related to a problem? Please describe.**
Based on bootstrap 4 documentation

This is what need to be done to complete button-group task in #11

https://getbootstrap.com/docs/4.3/components/button-group/

Master:
http://d1kybmg72qo0dt.cloudfront.net/build/global/branch/master/www/index.html

- [x] Basic button group
- [x] States
- [x] ~~Button toolbar~~
- [x] ~~Button toolbar with input group~~
- [x] Sizing
- [x] Nesting
- [x] Vertical

**Comment by helloimela** [comment]
Merged #42
