### ISSUE TITLE
Feature - Modal 4.0.0-beta

### ISSUE THREAD

**Issue by mmexvr** [scania/scania-theme#19]
**Is your feature request related to a problem? Please describe.**
Based on bootstrap 4 documentation

This is what need to be done to complete modal task in #11

https://getbootstrap.com/docs/4.3/components/modal/

Master:
http://d1kybmg72qo0dt.cloudfront.net/build/global/branch/master/www/index.html

- [x] Default modal, E.g Font, padding
- [x] ~~Close button on modal top~~
- [x] ~~Scrolling modal~~
- [x] ~~Inside Scrollable modal~~
- [x] ~~Vertically centered~~
- [x] ~~Tooltip and popovers inside modal~~
- [x] ~~Modal with grid~~
- [x] ~~Varying modal content~~
- [x] ~~Sizing~~

**Comment by helloimela** [comment]
Merged #21
