### ISSUE TITLE
Feature - Alerts 4.0.0-beta

### ISSUE THREAD

**Issue by mxuwku** [scania/scania-theme#20]
**Is your feature request related to a problem? Please describe.**
Based on bootstrap 4 documentation

This is what need to be done to complete Alerts task in #11 

https://getbootstrap.com/docs/4.3/components/alerts/

Master:
http://d1kybmg72qo0dt.cloudfront.net/build/global/branch/master/www/index.html

- [x] Alerts, E.g border-radius, font-weight, padding
- [x] Colours
- [x] Links
- [x] ~~Dismisable~~
- [x] ~~Additional content~~

**Comment by helloimela** [comment]
Merged to master PR #13
