### ISSUE TITLE
Feature - Breadcrumb 4.0.0-beta.1

### ISSUE THREAD

**Issue by mmexvr** [scania/scania-theme#26]
Is your feature request related to a problem? Please describe.
Based on bootstrap 4 documentation

This is what need to be done to complete breadcrumb task in #11

https://getbootstrap.com/docs/4.3/components/breadcrumb/

Master:
http://d1kybmg72qo0dt.cloudfront.net/build/global/branch/master/www/index.html

- [x] Link
- [x] Active
- [x] Padding

**Comment by helloimela** [comment]
Fixed in #24
