### ISSUE TITLE
Feature - Badge 4.0.0-beta.1

### ISSUE THREAD

**Issue by mmexvr** [scania/scania-theme#27]
**Is your feature request related to a problem? Please describe.**
Based on bootstrap 4 documentation

This is what need to be done to complete Badge task in #11 

https://getbootstrap.com/docs/4.3/components/badge/

Master:
http://d1kybmg72qo0dt.cloudfront.net/build/global/branch/master/www/index.html

- [x] ~~Reponsive to heading~~
- [x] ~~Inside buttons~~
- [x] Colors variation
- [x] Badge-pills
- [x] ~~Badge-links~~

**Comment by helloimela** [comment]
Fixed in #25
