### ISSUE TITLE
Feature - Pagination 4.0.0-beta.1

### ISSUE THREAD

**Issue by mmexvr** [scania/scania-theme#31]
**Is your feature request related to a problem? Please describe.**
Based on bootstrap 4 documentation

This is what need to be done to complete pagination task in #11 

https://getbootstrap.com/docs/4.3/components/pagination/

Master:
http://d1kybmg72qo0dt.cloudfront.net/build/global/branch/master/www/index.html

- [x] Default pagination, E.g font-size, padding
- [x] ~~With icons~~
- [x] Disabled and active
- [x] ~~Sizing~~
- [x] ~~Alignment~~

**Comment by helloimela** [comment]
Fixed in #30
