### ISSUE TITLE
Feature - List-group 4.0.0-beta.1

### ISSUE THREAD

**Issue by mmexvr** [scania/scania-theme#32]
**Is your feature request related to a problem? Please describe.**
Based on bootstrap 4 documentation

This is what need to be done to complete list-group task in #11 

https://getbootstrap.com/docs/4.3/components/list-group/

Master:
http://d1kybmg72qo0dt.cloudfront.net/build/global/branch/master/www/index.html

- [x] Default list-group
- [x] Active
- [x] ~~Disabeld~~
- [x] ~~Link and buttons~~
- [x] ~~Flush~~
- [x] ~~Horizotal~~
- [x] ~~Contextual classes~~
- [x] ~~Badges inside~~
- [x] ~~Custom content~~

**Comment by helloimela** [comment]
Fixed in #35
