### ISSUE TITLE
Bug - Alert function not mapping to color 

### ISSUE THREAD

**Issue by depascalis** [scania/scania-theme#73]
The function generating classes for secondary and light alerts is not mapping `background-color` and `color` to a color.

https://github.com/scania/scania-theme/blob/b3a2a7fbc7bd1e13db5d0597eb37001816a9d2ca/src/styles/elements/c-global-style.scss#L96

https://github.com/scania/scania-theme/blob/b3a2a7fbc7bd1e13db5d0597eb37001816a9d2ca/src/styles/elements/c-global-style.scss#L98

However, the whole function for alerts is incomplete and needs more work. Apart from this, here are some points so it's not forgotten.

- .alert-dark and .alert-primary are not included
- .alert-* .alert-link is missing. See Bootstrap [mixin](https://github.com/twbs/bootstrap/blob/b4e957d360899c2555cb29a3ae4589405883bba9/scss/mixins/_alert.scss#L6)

**Comment by helloimela** [comment]
@depascalis we're not overriding .alert-link from bootstrap. If you have a link inside alert, you can just put an `a` element inside, you don't need to add `.alert-link `class. 
Do you think we need `.alert-primary, .alert-secondary & .alert-dark` ? At the moment we don't see the purpose of alert primary, dark, light, and secondary, that's why we are not adding those. Light is there in code but we think to remove it from alert. But if you have a use case where those classes are needed let us know!

**Comment by depascalis** [comment]
@helloimela I'm thinking, since it's based on Bootstrap, it should maybe support all default classes. Some third-party libraries rely on Bootstrap and it's better if all classes are adjusted for the scania-theme instead of using a default class. This will force the developer to add customizations that might not be in line with Scanias design rules or profile. Some might also use a class unwittingly that it's a Bootstrap default and not adapted to the scania-theme. It will also simplify migrating a project to the scania-theme if all classes are supported.

I agree though that there's a lot of unneeded classes but I can't decide on how to tackle them, if one should include them or not.

**Comment by helloimela** [comment]
@depascalis thank you for the feedback. It's a good thought! I think developers need to get their hands 'dirty' and modify the classes according to what they need in the interface. Best practices for classes I think as less as we can add to reduce complexity ;) 

We build Corporate UI extending bootstrap classes but it does not mean we will use all of their classes, we will use only the one that can help us to achieve Scania looks and feel. So, our priority right now is not replacing all bootstrap classes but rather on focusing on the interaction pattern. But it's a good thought from you and probably if we have good design & good use-case for dark, light,secondary, we will add it in the future. We welcome for contribution as well :)
